version: 1
disable_existing_loggers: False
formatters:
    auto_push:
        format: "%(asctime)s [%(levelname)s] - %(name)s - %(funcName)s - %(filename)s[%(lineno)d]: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: auto_push
        stream: ext://sys.stdout

    info_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: auto_push
        filename: log/info.log
        maxBytes: 104857600 # 10MB
        backupCount: 20
        encoding: utf8

    error_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: auto_push
        filename: log/errors.log
        maxBytes: 104857600 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    modulename:
        level: ERROR
        handlers: [console]
        propagate: no


root:
    level: INFO
    handlers: [console, info_handler, error_handler]
